export const priceEntryTableConfig = [
  {
    seriesItemTypeCode: "pi-single-with-ref",
    sort: {
      name: "priceSeriesName",
      order: "ASC",
    },
    columns: [
      {
        field: "priceSeriesName",
        headerName: "Price series",
        cellDataType: "text",
        displayOrder: 0,
        editable: false,
        pinned: "left",
      },
      {
        field: "unitDisplay",
        headerName: "Units",
        cellDataType: "text",
        displayOrder: 1,
        editable: false,
      },
      {
        field: "lastAssessmentPrice",
        headerName: "Last assessment price",
        cellDataType: "text",
        displayOrder: 2,
        editable: false,
        type: "rightAligned",
      },
      {
        field: "lastAssessmentDate",
        headerName: "Last assessment date",
        cellDataType: "text",
        displayOrder: 3,
        editable: false,
      },
      {
        field: "assessmentMethod",
        headerName: "Assessment method",
        cellDataType: "object",
        values: ["Assessed", "Premium/Discount"],
        displayOrder: 4,
        editable: true,
      },
      {
        field: "referencePrice",
        headerName: "Reference price",
        cellDataType: "number",
        displayOrder: 5,
        editable: false,
        editableWhen: {
          field: "assessmentMethod",
          value: "Premium/Discount",
        },
      },
      {
        field: "premiumDiscount",
        headerName: "Premium/Discount",
        cellDataType: "number",
        displayOrder: 6,
        editable: false,
        editableWhen: {
          field: "assessmentMethod",
          value: "Premium/Discount",
        },
        type: "rightAligned",
      },
      {
        field: "price",
        headerName: "Price",
        displayOrder: 7,
        cellDataType: "number",
        editable: false,
        editableWhen: {
          field: "assessmentMethod",
          value: "Assessed",
        },
        type: "rightAligned",
      },
      {
        field: "priceDelta",
        headerName: "Change",
        cellDataType: "priceDelta",
        displayOrder: 8,
        editable: false,
        type: "rightAligned",
        customConfig: {
          priceDelta: {
            priceField: "price",
            priceDeltaField: "priceDelta",
            precisionField: "valueDisplayPrecission",
          },
        },
      },
      {
        field: "dataUsed",
        headerName: "Data used",
        cellDataType: "object",
        values: [
          "Bid/offer",
          "Transaction",
          "Spread",
          "Fundamentals",
          "Interpolation/extrapolation",
        ],
        displayOrder: 9,
        editable: true,
      },
    ],
  },
  {
    seriesItemTypeCode: "range",
    sort: {
      name: "priceSeriesName",
      order: "ASC",
    },
    columns: [
      {
        field: "priceSeriesName",
        headerName: "Price series",
        cellDataType: "text",
        displayOrder: 0,
        editable: false,
        pinned: "left",
      },
      {
        field: "unitDisplay",
        headerName: "Units",
        cellDataType: "text",
        displayOrder: 1,
        editable: false,
      },
      {
        field: "lastAssessmentPrice",
        headerName: "Last assessment price",
        cellDataType: "text",
        displayOrder: 2,
        editable: false,
        type: "rightAligned",
      },
      {
        field: "lastAssessmentDate",
        headerName: "Last assessment date",
        cellDataType: "text",
        displayOrder: 3,
        editable: false,
      },
      {
        field: "priceLow",
        headerName: "Low price",
        cellDataType: "number",
        displayOrder: 4,
        editable: true,
        type: "rightAligned",
      },
      {
        field: "priceLowDelta",
        headerName: "Low change",
        cellDataType: "priceDelta",
        displayOrder: 5,
        editable: false,
        type: "rightAligned",
        customConfig: {
          priceDelta: {
            priceField: "priceLow",
            priceDeltaField: "priceLowDelta",
            precisionField: "valueDisplayPrecission",
          },
        },
      },
      {
        field: "priceMid",
        headerName: "Mid price",
        cellDataType: "number",
        displayOrder: 6,
        editable: false,
        type: "rightAligned",
      },
      {
        field: "priceMidDelta",
        headerName: "Mid change",
        cellDataType: "priceDelta",
        displayOrder: 7,
        editable: false,
        type: "rightAligned",
        customConfig: {
          priceDelta: {
            priceField: "priceMid",
            priceDeltaField: "priceMidDelta",
            precisionField: "valueDisplayPrecission",
          },
        },
      },
      {
        field: "priceHigh",
        headerName: "High price",
        cellDataType: "number",
        displayOrder: 8,
        editable: true,
        type: "rightAligned",
      },
      {
        field: "priceHighDelta",
        headerName: "High change",
        cellDataType: "priceDelta",
        displayOrder: 9,
        editable: false,
        type: "rightAligned",
        customConfig: {
          priceDelta: {
            priceField: "priceHigh",
            priceDeltaField: "priceHighDelta",
            precisionField: "valueDisplayPrecission",
          },
        },
      },
    ],
  },
];
