import { GridConfigurationType } from "./contentBlockDefinition";

export const GridConfiguration: GridConfigurationType[] = [
  {
    _id: {
      $oid: "660d688f832da3b7d361a882",
    },
    series_item_type_code: "single_value_with_reference",
    sort: {
      name: "priceSeriesName",
      order: "ASC",
    },
    // @ts-ignore
    columns: [
      {
        field: "priceSeriesName",
        header_name: "Price series",
        cell_data_type: "text",
        display_order: 0,
        editable: false,
        pinned: "left",
      },
      {
        field: "period",
        header_name: "Period",
        cell_data_type: "text",
        display_order: 1,
        editable: false,
      },
      {
        field: "unitDisplay",
        header_name: "Units",
        cell_data_type: "text",
        display_order: 2,
        editable: false,
      },
      {
        field: "assessmentMethod",
        header_name: "Assessment method",
        cell_data_type: "object",
        values: ["Assessed", "Premium/Discount"],
        display_order: 3,
        editable: true,
        tooltip_field: "assessmentMethod",
        cell_type: "select",
      },
      {
        field: "referencePrice",
        header_name: "Reference price",
        cell_data_type: "number",
        display_order: 4,
        editable: false,
        editable_when: {
          field: "assessmentMethod",
          value: "Premium/Discount",
        },
        tooltip_field: "referencePrice",
        cell_type: "input",
      },
      {
        field: "premiumDiscount",
        header_name: "Premium/Discount",
        cell_data_type: "number",
        display_order: 5,
        editable: false,
        editable_when: {
          field: "assessmentMethod",
          value: "Premium/Discount",
        },
        type: "rightAligned",
        tooltip_field: "premiumDiscount",
        cell_type: "input",
      },
      {
        field: "price",
        header_name: "Price",
        display_order: 6,
        cell_data_type: "number",
        editable: false,
        editable_when: {
          field: "assessmentMethod",
          value: "Assessed",
        },
        type: "rightAligned",
        tooltip_field: "price",
        cell_type: "input",
      },
      {
        field: "dataUsed",
        header_name: "Data used",
        cell_data_type: "object",
        values: [
          "Bid/offer",
          "Transaction",
          "Spread",
          "Fundamentals",
          "Interpolation/extrapolation",
        ],
        display_order: 7,
        editable: true,
        tooltip_field: "dataUsed",
        cell_type: "select",
      },
      {
        field: "priceDelta",
        header_name: "Change",
        cell_data_type: "priceDelta",
        display_order: 8,
        editable: false,
        type: "rightAligned",
        custom_config: {
          price_delta: {
            price_field: "price",
            price_delta_field: "priceDelta",
            precision_field: "valueDisplayPrecission",
          },
        },
      },
      {
        field: "lastAssessmentPrice",
        header_name: "Last assessment price",
        cell_data_type: "text",
        display_order: 9,
        editable: false,
        type: "rightAligned",
      },
      {
        field: "lastAssessmentDate",
        header_name: "Last assessment date",
        cell_data_type: "text",
        display_order: 10,
        editable: false,
      },
    ],
  },
  {
    _id: {
      $oid: "660d688f832da3b7d361a883",
    },
    series_item_type_code: "range",
    sort: {
      name: "priceSeriesName",
      order: "ASC",
    },
    // @ts-ignore
    columns: [
      {
        field: "priceSeriesName",
        header_name: "Price series",
        cell_data_type: "text",
        display_order: 0,
        editable: false,
        pinned: "left",
      },
      {
        field: "unitDisplay",
        header_name: "Units",
        cell_data_type: "text",
        display_order: 1,
        editable: false,
      },
      {
        field: "priceLow",
        header_name: "Low price",
        cell_data_type: "number",
        display_order: 2,
        editable: true,
        type: "rightAligned",
        tooltip_field: "priceLow",
        cell_type: "input",
      },
      {
        field: "priceHigh",
        header_name: "High price",
        cell_data_type: "number",
        display_order: 3,
        editable: true,
        type: "rightAligned",
        tooltip_field: "priceHigh",
        cell_type: "input",
      },
      {
        field: "priceLowDelta",
        header_name: "Low change",
        cell_data_type: "priceDelta",
        display_order: 4,
        editable: false,
        type: "rightAligned",
        custom_config: {
          price_delta: {
            price_field: "priceLow",
            price_delta_field: "priceLowDelta",
            precision_field: "valueDisplayPrecission",
          },
        },
      },
      {
        field: "priceHighDelta",
        header_name: "High change",
        cell_data_type: "priceDelta",
        display_order: 5,
        editable: false,
        type: "rightAligned",
        custom_config: {
          price_delta: {
            price_field: "priceHigh",
            price_delta_field: "priceHighDelta",
            precision_field: "valueDisplayPrecission",
          },
        },
      },
      {
        field: "priceMid",
        header_name: "Mid price",
        cell_data_type: "number",
        display_order: 6,
        editable: false,
        type: "rightAligned",
      },
      {
        field: "priceMidDelta",
        header_name: "Mid change",
        cell_data_type: "priceDelta",
        display_order: 7,
        editable: false,
        type: "rightAligned",
        custom_config: {
          price_delta: {
            price_field: "priceMid",
            price_delta_field: "priceMidDelta",
            precision_field: "valueDisplayPrecission",
          },
        },
      },
      {
        field: "lastAssessmentPrice",
        header_name: "Last assessment price",
        cell_data_type: "text",
        display_order: 8,
        editable: false,
        type: "rightAligned",
      },
      {
        field: "lastAssessmentDate",
        header_name: "Last assessment date",
        cell_data_type: "text",
        display_order: 9,
        editable: false,
      },
    ],
  },
];
