export const TITLE_MAX_CHAR_LENGTH = 65;

export const WORKFLOW_EVENTS = 'WorkflowEvents';

export const PRICE_AUTHORING_EVENTS = 'PriceAuthoringEvents';

export const WORKFLOW_ACTIONS = {
  PUBLISH: 'PUBLISH',
  INITIATE_CORRECTION: 'INITIATE_CORRECTION',
  SEND_FOR_REVIEW: 'SEND_FOR_REVIEW',
  SEND_BACK: 'SEND_BACK',
  APPROVE: 'APPROVE',
  CANCEL: 'CANCEL',
  CORRECTION_PUBLISHED: 'CORRECTION_PUBLISHED',
  APPROVE_CORRECTION: 'APPROVE_CORRECTION',
};

export const NMA_ACTIONS = {
  START_NMA: 'START_NMA',
  CANCEL_NMA: 'CANCEL_NMA',
};

export const WORKFLOW_STATUS = {
  READY_TO_START: 'READY TO START',
  READY_TO_PUBLISH: 'READY TO PUBLISH',
  CORRECTION_READY_TO_PUBLISH: 'CORRECTION READY TO PUBLISH',
  PUBLISHED: 'PUBLISHED',
  CORRECTION_PUBLISHED: 'CORRECTION PUBLISHED',
  DRAFT: 'DRAFT',
  CORRECTION_DRAFT: 'CORRECTION DRAFT',
  READY_FOR_REVIEW: 'READY FOR REVIEW',
  CORRECTION_READY_FOR_REVIEW: 'CORRECTION READY FOR REVIEW',
  IN_REVIEW: 'IN REVIEW',
  CORRECTION_IN_REVIEW: 'CORRECTION IN REVIEW',
  SENT_BACK: 'SENT BACK',
};

export const PRICE_DISPLAY_WORKFLOW_STATUS = {
  READY_TO_START: 'READY_TO_START',
  READY_TO_PUBLISH: 'READY_TO_PUBLISH',
  CORRECTION_READY_TO_PUBLISH: 'CORRECTION_READY_TO_PUBLISH',
  PUBLISHED: 'PUBLISHED',
  CORRECTION_PUBLISHED: 'CORRECTION_PUBLISHED',
  DRAFT: 'DRAFT',
  CORRECTION_DRAFT: 'CORRECTION_DRAFT',
  READY_FOR_REVIEW: 'READY_FOR_REVIEW',
  CORRECTION_READY_FOR_REVIEW: 'CORRECTION_READY_FOR_REVIEW',
  IN_REVIEW: 'IN_REVIEW',
  CORRECTION_IN_REVIEW: 'CORRECTION_IN_REVIEW',
  SENT_BACK: 'SENT_BACK',
};

export const PUBLISH_WORKFLOW_STATUS = {
  PUBLISHED: 'PUBLISHED',
  CORRECTION_PUBLISHED: 'CORRECTION_PUBLISHED',
};

export const DATE_TIME_STRING_FORMAT = 'dd MMM yyyy HH:mm';

export const DATE_TIME_PLACEHOLDER = 'dd mmm yyyy hh:mm';

export const SERIES_ITEM_TYPE_CODE = {
  PI_RANGE: 'pi-range',
};

export const PRICE_DELTA_TYPES = {
  NON_MARKET_ADJUSTMENT: 'NONMKTADJ',
  REGULAR: 'REGULAR',
};

export const ERROR_CODES = {
  NOT_ALL_REFERENCE_PRICE_SERIES_ARE_PUBLISHED: 'NOT_ALL_REFERENCE_PRICE_SERIES_ARE_PUBLISHED',
  CORRECTION_CONTAINS_NO_CHANGES: 'CORRECTION_CONTAINS_NO_CHANGES',
  NOT_ALL_INPUTS_ARE_PUBLISHED: 'NOT_ALL_INPUTS_ARE_PUBLISHED',
};

export const REVIEW_ACTIONS = [
  WORKFLOW_ACTIONS.SEND_FOR_REVIEW,
  WORKFLOW_ACTIONS.APPROVE,
  WORKFLOW_ACTIONS.APPROVE_CORRECTION,
];
